### ISSUE TITLE
scaffold.py中train方法中的逻辑问题

### ISSUE THREAD

**Issue by byyb233** [KarhouTam/SCAFFOLD-PyTorch#1]
self.c_local = c_new
# calc control_delta
for c_d, c_n, c_l in zip(c_delta, c_new, self.c_local):
    c_d.data += c_n.data - c_l.data
上述代码是否存在逻辑错误？
c_d的结果一直为0

**Comment by KarhouTam** [comment]
是的😂. 感谢指出错误. 应该将 `self.c_local = c_new` 移至更新 `c_delta` 下方。 我会尽快修改代码

**Comment by KarhouTam** [comment]
已修改代码。可以 pull 下最新的代码。再次感谢你的指正。🙏
