### ISSUE TITLE
SACFFOLD中的OPTIMIZER是否还是SGD

### ISSUE THREAD

**Issue by chenrxi** [KarhouTam/SCAFFOLD-PyTorch#3]
我没有找到SCAFFOLD更新权重w的代码段

**Comment by KarhouTam** [comment]
local optimizer 是 sgd:
 我没有额外设置 `SCAFFOLDTrainer` 的 `optimizer`, 所以沿用父类的 `ClientBase.optimizer`.
以下代码来自 `.src/client/base.py` 的 `__init__()`.
```
        self.optimizer: torch.optim.Optimizer = torch.optim.SGD(
            self.model.parameters(), lr=local_lr
        )
```
 server 端则是用各 client 的 local model 训练前后的 difference 直接取平均后作为梯度来更新:
以下代码来自 `./src/server/scaffold.py` 的 `aggregate()`
```
        # update global model
        weight = torch.tensor(
            [
                1 / self.args.client_num_per_round
                for _ in range(self.args.client_num_per_round)
            ],
            device=self.device,
        )
        for param, y_del in zip(trainable_parameter, zip(*y_delta_cache)):
            x_del = torch.sum(weight * torch.stack(y_del, dim=-1), dim=-1)
            param.data += self.global_lr * x_del

        # update global control
        weight = torch.tensor(
            [
                self.args.client_num_per_round / len(self.client_id_indices)
                for _ in range(self.args.client_num_per_round)
            ],
            device=self.device,
        )
```

**Comment by chenrxi** [comment]
SERVER我是清楚的，不清楚的是SCAFFOLD的client端的更新。
原论文的算法是：
<img width="834" alt="image" src="https://user-images.githubusercontent.com/60959000/189683925-af744eca-09ab-40d4-8531-64b0121e813c.png">
直接根据权重的梯度更新参数，不对吧

**Comment by KarhouTam** [comment]
抱歉， 在重构代码后没有对代码进行复查😵。我会尽快修改代码。🙏

**Comment by chenrxi** [comment]
哈哈没事，我怀疑是我理解错了

**Comment by KarhouTam** [comment]
感谢指正🙏。

**Comment by chenrxi** [comment]
问一下这套代码训练CIFAR100需要多长时间？

**Comment by KarhouTam** [comment]
代码已经更新了。应该是没错了😂。欢迎拉取最新的代码。但在训练某些数据库时可能会出现不稳定或者过拟合的现象。我感觉应该是我用的 model 跟 paper 的不一样或者我的数据库划分方法跟 paper 的不一样导致的。算法流程上来说应该没有大的问题。

**Comment by chenrxi** [comment]
get
