### ISSUE TITLE
How much memory is needed to use EMNIST datasets running SCAFFOLD algorithm?

### ISSUE THREAD

**Issue by chenzhigang00** [KarhouTam/SCAFFOLD-PyTorch#5]
Hi,
Your work is excellent, I like it, but I am confronted with some memory problem.

When I ran the `SCAFFOLD `algorithm on the `EMNIST` dataset using Linux, my program was killed by the operating system. After debugging, I found that the problem might be due to this:`data\utils\util.py line31-32`
![image](https://github.com/user-attachments/assets/d81a6340-71d5-4419-af54-357fcb2c1a5a)

That is, the pickle file is too big(2.39GB), making the memory overflow.
![image](https://github.com/user-attachments/assets/b539ba94-c326-4ef7-a9ab-45747c8fbb02)

Although I have increased the swap area size to 4G, the error still occur.
![image](https://github.com/user-attachments/assets/2f63a96a-686c-4429-bdf5-18a35bc2d0f0)

Is there any suggestion to deal with this problem? I am looking forward to your guidance.
Thanks!

**Comment by KarhouTam** [comment]
First, many thanks to you for your attention to this repo and the appreciation.

Sorry I don't maintain this repo for a long time.

If you can, please switch to use my another repo: [FL-bench](https://github.com/KarhouTam/FL-bench), which also integrates SCAFFOLD (and EMNIST ofc) and is still being maintained by me.

**Comment by chenzhigang00** [comment]
No problem, thanks for your quick and kind reply!
